db.url=jdbc:mysql://localhost:3306/kasir_pendem?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta
db.username=root
db.password=
app.paper.size=80
app.printer.name=
app.topup.min=1000
app.topup.max=5000000
